jobs:
  - name: deploy-git-branching_runCI
    type: runCI
    flags:
      - deploy-git-branching
    steps:
      - OUT: deploy-git-branching-image-develop
      - OUT: deploy-git-branching-image-release
      - OUT: deploy-git-branching-image-hotfix

  - name: deploy-git-branching-manifest-develop
    type: manifest
    flags:
      - deploy-git-branching
    steps:
     - IN: deploy-git-branching-image-develop
     - IN: deploy-git-branching-docker-options
     - IN: deploy-git-branching-params
     - IN: deploy-git-branching-replicas

  - name: deploy-git-branching-deploy-develop
    type: deploy
    flags:
      - deploy-git-branching
    steps:
      - IN: deploy-git-branching-manifest-develop
      - IN: deploy-git-branching-ecs-cluster-develop
      - TASK: managed
        deployMethod: replace
